In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("EPOCH3BARTALL.csv")

In [14]:
df

,Unnamed: 0.1,Unnamed: 0,qid,OU model2 answer span,OU model2 start,OU model2 end,OU model2 score,SA model2 answer span,SA model2 start,SA model2 end,...,SA roberta score,OU retro answer span,SA retro answer span,OU sgnet answer span,SA sgnet answer span,context,uq,labels,suggested aq,predicted_labels
0,0,0,5ad39d53604f3c001a3fe8d1,The Normans,0,11,2.337817e-04,The Normans,0,11,...,9.732896e-01,<No Answer>. The question is not answerable ac...,the normans,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th an...,E
1,1,1,5ad39d53604f3c001a3fe8d2,"Normandy,",136,146,5.196336e-07,"Normandy,",136,146,...,4.917059e-08,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,What is France a region of?,I,What is France a region of?,N
2,2,2,5ad39d53604f3c001a3fe8d3,West Francia.,556,570,1.021575e-06,West Francia.,556,570,...,5.532054e-09,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who did King Charles III swear fealty to?,I,Who did King Charles III swear fealty to?,N
3,3,3,5ad39d53604f3c001a3fe8d4,"first half of the 10th century,",652,684,1.761726e-09,"first half of the 10th century,",652,684,...,5.637674e-01,<No Answer>. The question is not answerable ac...,first half of the 10th century,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,When did the Frankish identity emerge?,E,When did the Normans identity emerge?,E
4,4,4,5ad3a266604f3c001a3fea27,"political, cultural and military",30,63,1.606901e-07,"political, cultural and military",30,63,...,8.276052e-07,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,"political, cultural and military",p,"The Norman dynasty had a major political, cult...",What type of major impact did the Norman dynas...,X,What type of major impact did the Norman dynas...,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5940,5940,5940,5ad28a57d7d075001a4299b3,nonconservative forces,187,210,1.125980e-08,nonconservative forces act to change the inte...,187,261,...,4.124932e-02,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The connection between macroscopic nonconserva...,What does not change macroscopic closed systems?,N,What does change macroscopic closed systems?,N
5941,5941,5941,5ad28ad0d7d075001a4299cc,newton:,69,77,5.952701e-07,newton:,69,77,...,1.539261e-10,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What does not have a metric counterpart?,N,What does not have a metric counterpart?,N
5942,5942,5942,5ad28ad0d7d075001a4299cd,kilogram-force,81,96,1.338633e-07,kilogram-force,81,96,...,2.608475e-08,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What is the force exerted by standard gravity ...,E,What is the force exerted by standard gravity ...,N
5943,5943,5943,5ad28ad0d7d075001a4299ce,kilogram-force,194,209,4.873671e-08,kilogram-force,194,209,...,9.138619e-10,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What force leads to a commonly used unit of mass?,E,What force leads to a commonly used unit of mass?,N
5944,5944,5944,5ad28ad0d7d075001a4299cf,kilogram-force,81,96,1.914169e-08,kilogram-force,382,397,...,6.875408e-01,<No Answer>. The question is not answerable ac...,the kilogram-force,NaN,NaN,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What force is not part of the modern SI system?,N

In [4]:
new_data = pd.read_csv("dev_sal.csv")

In [5]:
new_data

,Unnamed: 0.1,Unnamed: 0,qid,context,original_question,label,answer span,original_answer_span,answer_sentence
0,5,5,5ad39d53604f3c001a3fe8d1,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,"('', '')",Normans,The Normans (Norman: Nourmands; French: Norman...
1,6,6,5ad39d53604f3c001a3fe8d2,The Normans (Norman: Nourmands; French: Norman...,What is France a region of?,I,"('', '')",Normandy,The Normans (Norman: Nourmands; French: Norman...
2,7,7,5ad39d53604f3c001a3fe8d3,The Normans (Norman: Nourmands; French: Norman...,Who did King Charles III swear fealty to?,I,"('', '')",Rollo,"They were descended from Norse (""Norman"" comes..."
3,8,8,5ad39d53604f3c001a3fe8d4,The Normans (Norman: Nourmands; French: Norman...,When did the Frankish identity emerge?,E,"('', '')",10th century,The distinct cultural and ethnic identity of t...
4,12,12,5ad3a266604f3c001a3fea27,"The Norman dynasty had a major political, cult...",What type of major impact did the Norman dynas...,X,"('', '')","political, cultural and military","The Norman dynasty had a major political, cult..."
...,...,...,...,...,...,...,...,...,...
5940,11863,11863,5ad28a57d7d075001a4299b3,The connection between macroscopic nonconserva...,What does not change macroscopic closed systems?,N,"('', '')",nonconservative forces,The connection between macroscopic nonconserva...
5941,11869,11869,5ad28ad0d7d075001a4299cc,"The pound-force has a metric counterpart, less...",What does not have a metric counterpart?,N,"('', '')",pound-force,"The pound-force has a metric counterpart, less..."
5942,11870,11870,5ad28ad0d7d075001a4299cd,"The pound-force has a metric counterpart, less...",What is the force exerted by standard gravity ...,E,"('', '')",kilogram-force,"The pound-force has a metric counterpart, less..."
5943,11871,11871,5ad28ad0d7d075001a4299ce,"The pound-force has a metric counterpart, less...",What force leads to a commonly used unit of mass?,E,"('', '')",kilogram-force,"The pound-force has a metric counterpart, less..."
5944,11872,11872,5ad28ad0d7d075001a4299cf,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,"('', '')",kilogram-force,"The pound-force has a metric counterpart, less..."

In [6]:
context = new_data['context'].tolist()
unans = new_data["original_question"].tolist()
labels = new_data['label'].tolist()
df['context'] = context
df['uq'] = unans
df['labels'] = labels

In [7]:
df

,Unnamed: 0.1,Unnamed: 0,qid,OU model2 answer span,OU model2 start,OU model2 end,OU model2 score,SA model2 answer span,SA model2 start,SA model2 end,...,SA roberta score,OU retro answer span,SA retro answer span,OU sgnet answer span,SA sgnet answer span,context,uq,labels,suggested aq,predicted_labels
0,0,0,5ad39d53604f3c001a3fe8d1,The Normans,0,11,2.337817e-04,The Normans,0,11,...,9.732896e-01,<No Answer>. The question is not answerable ac...,the normans,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th an...,E
1,1,1,5ad39d53604f3c001a3fe8d2,"Normandy,",136,146,5.196336e-07,"Normandy,",136,146,...,4.917059e-08,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,What is France a region of?,I,What is France a region of?,N
2,2,2,5ad39d53604f3c001a3fe8d3,West Francia.,556,570,1.021575e-06,West Francia.,556,570,...,5.532054e-09,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who did King Charles III swear fealty to?,I,Who did King Charles III swear fealty to?,N
3,3,3,5ad39d53604f3c001a3fe8d4,"first half of the 10th century,",652,684,1.761726e-09,"first half of the 10th century,",652,684,...,5.637674e-01,<No Answer>. The question is not answerable ac...,first half of the 10th century,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,When did the Frankish identity emerge?,E,When did the Normans identity emerge?,E
4,4,4,5ad3a266604f3c001a3fea27,"political, cultural and military",30,63,1.606901e-07,"political, cultural and military",30,63,...,8.276052e-07,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,"political, cultural and military",p,"The Norman dynasty had a major political, cult...",What type of major impact did the Norman dynas...,X,What type of major impact did the Norman dynas...,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5940,5940,5940,5ad28a57d7d075001a4299b3,nonconservative forces,187,210,1.125980e-08,nonconservative forces act to change the inte...,187,261,...,4.124932e-02,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The connection between macroscopic nonconserva...,What does not change macroscopic closed systems?,N,What does change macroscopic closed systems?,N
5941,5941,5941,5ad28ad0d7d075001a4299cc,newton:,69,77,5.952701e-07,newton:,69,77,...,1.539261e-10,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What does not have a metric counterpart?,N,What does not have a metric counterpart?,N
5942,5942,5942,5ad28ad0d7d075001a4299cd,kilogram-force,81,96,1.338633e-07,kilogram-force,81,96,...,2.608475e-08,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What is the force exerted by standard gravity ...,E,What is the force exerted by standard gravity ...,N
5943,5943,5943,5ad28ad0d7d075001a4299ce,kilogram-force,194,209,4.873671e-08,kilogram-force,194,209,...,9.138619e-10,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What force leads to a commonly used unit of mass?,E,What force leads to a commonly used unit of mass?,N
5944,5944,5944,5ad28ad0d7d075001a4299cf,kilogram-force,81,96,1.914169e-08,kilogram-force,382,397,...,6.875408e-01,<No Answer>. The question is not answerable ac...,the kilogram-force,NaN,NaN,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What force is not part of the modern SI system?,N

In [8]:
with open("bart_epoch3.txt", 'r') as file:
    lines = file.readlines()

# Remove newline characters from each line
lines = [line.strip() for line in lines]
#lines.pop()

In [9]:
df['suggested aq'] = lines

In [10]:
df

,Unnamed: 0.1,Unnamed: 0,qid,OU model2 answer span,OU model2 start,OU model2 end,OU model2 score,SA model2 answer span,SA model2 start,SA model2 end,...,SA roberta score,OU retro answer span,SA retro answer span,OU sgnet answer span,SA sgnet answer span,context,uq,labels,suggested aq,predicted_labels
0,0,0,5ad39d53604f3c001a3fe8d1,The Normans,0,11,2.337817e-04,The Normans,0,11,...,9.732896e-01,<No Answer>. The question is not answerable ac...,the normans,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who gave their name to Normandy in the 1000's ...,I,Who gave their name to Normandy in the 10th an...,E
1,1,1,5ad39d53604f3c001a3fe8d2,"Normandy,",136,146,5.196336e-07,"Normandy,",136,146,...,4.917059e-08,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,What is France a region of?,I,What is France a region of?,N
2,2,2,5ad39d53604f3c001a3fe8d3,West Francia.,556,570,1.021575e-06,West Francia.,556,570,...,5.532054e-09,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,Who did King Charles III swear fealty to?,I,Who did King Charles III swear fealty to?,N
3,3,3,5ad39d53604f3c001a3fe8d4,"first half of the 10th century,",652,684,1.761726e-09,"first half of the 10th century,",652,684,...,5.637674e-01,<No Answer>. The question is not answerable ac...,first half of the 10th century,NaN,NaN,The Normans (Norman: Nourmands; French: Norman...,When did the Frankish identity emerge?,E,When did the Normans identity emerge?,E
4,4,4,5ad3a266604f3c001a3fea27,"political, cultural and military",30,63,1.606901e-07,"political, cultural and military",30,63,...,8.276052e-07,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,"political, cultural and military",p,"The Norman dynasty had a major political, cult...",What type of major impact did the Norman dynas...,X,What type of major impact did the Norman dynas...,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5940,5940,5940,5ad28a57d7d075001a4299b3,nonconservative forces,187,210,1.125980e-08,nonconservative forces act to change the inte...,187,261,...,4.124932e-02,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,The connection between macroscopic nonconserva...,What does not change macroscopic closed systems?,N,What does change macroscopic closed systems?,N
5941,5941,5941,5ad28ad0d7d075001a4299cc,newton:,69,77,5.952701e-07,newton:,69,77,...,1.539261e-10,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What does not have a metric counterpart?,N,What does not have a metric counterpart?,N
5942,5942,5942,5ad28ad0d7d075001a4299cd,kilogram-force,81,96,1.338633e-07,kilogram-force,81,96,...,2.608475e-08,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What is the force exerted by standard gravity ...,E,What is the force exerted by standard gravity ...,N
5943,5943,5943,5ad28ad0d7d075001a4299ce,kilogram-force,194,209,4.873671e-08,kilogram-force,194,209,...,9.138619e-10,<No Answer>. The question is not answerable ac...,<No Answer>. The question is not answerable ac...,NaN,NaN,"The pound-force has a metric counterpart, less...",What force leads to a commonly used unit of mass?,E,What force leads to a commonly used unit of mass?,N
5944,5944,5944,5ad28ad0d7d075001a4299cf,kilogram-force,81,96,1.914169e-08,kilogram-force,382,397,...,6.875408e-01,<No Answer>. The question is not answerable ac...,the kilogram-force,NaN,NaN,"The pound-force has a metric counterpart, less...",What force is part of the modern SI system?,N,What force is not part of the modern SI system?,N

In [11]:
df.to_csv("BARTEPOCH3RESULTS.csv")